### ISSUE TITLE
tacc not found

### ISSUE THREAD

**Issue by lucevers** [jeroennijhof/pam_tacplus#89] opened 2017-03-19 16:12 UTC
Seems that tacc is not compiled.
  Could not found the program after installing pam_tacplus.

**Comment by pprindeville** [comment] 2017-03-20 18:06
Can you attach the output of your `make`?  Not giving a lot of useful information to go by here.

**Comment by exaraxe** [comment] 2017-03-30 18:50
The issue is not announced in the make process, but it is if you attempt to compile the tacc.c manually:

```
# gcc tacc.c -o tacc
tacc.c:30:26: fatal error: openssl/rand.h: No such file or directory
 #include <openssl/rand.h>
                          ^
compilation terminated.

```


This issue can be fixed by either installing libssl-dev in Debian or openssl-devel in RHEL base.

**Comment by pprindeville** [comment] 2017-03-30 18:53
> This issue can be fixed by either installing libssl-dev in Debian or openssl-devel in RHEL base.

Of course the package containing the headers needs to be present to compile.  Also, when you compile manually you're not passing in all the flags that a make-based compile would, so of course it's not going to work properly.

Neither of these is really a bug.  That's normal usage.

**Comment by exaraxe** [comment] 2017-03-30 20:04
> when you compile manually you're not passing in all the flags that a make-based compile would

Correct, I should've included the extended piece instead of the short one where I was replicating the make flags.

**Comment by pprindeville** [comment] 2017-03-30 20:09
That's not really the point.  If you want to (re-)compile `tacc`, then you do so as:

```
make tacc
```

**Comment by exaraxe** [comment] 2017-03-30 20:15
Worth noting, in Debian 4.7.5, you also need to replace -Werror with -Wno-deprecated to compile successfully with all dependencies. tacc is working for me at this time. Thanks.

**Comment by pprindeville** [comment] 2017-03-30 20:18
I don't think you need to _replace_ `-Werror` so much as supplement it as `-Werror -Wno-error=deprecated`.  Can you post the errors that you're seeing when you build?  And why are you using such an old version of Debian?  I don't think anyone expects a current project to build under such an old release. Etch is now 10 years old.

**Comment by exaraxe** [comment] 2017-03-30 20:27
In short, make was running with no issue (reported), but it was never spitting out the tacc client.
So I replicated as many of the flags from make as I could, and realized it was missing libssl. 
Once that was fixed, it was failing to compile due to deprecation errors.
That's when I pulled -Werror (in place of the more sensible -Wno-error=deprecated)

So, had I not needed tacc, it likely would have never been noticed.

**Comment by pprindeville** [comment] 2017-03-30 20:43
> Once that was fixed, it was failing to compile due to deprecation errors.

Without seeing the previously requested errors, I can't tell if that's definitively true or not, but I strongly suspect that the errors have to do with your using a very old version of Debian (and hence a very old version of OpenSSL, probably pre 1.0.0).

**Comment by pprindeville** [comment] 2017-03-31 00:23
Can you post your compilation messages from an unmodified cloning?

**Comment by pprindeville** [comment] 2017-04-14 19:09
Can't fix it without more information so closing the issue.

**Closed by pprindeville** 2017-04-14 19:09 UTC
